spring :
  application:
    name: Config-dev
eureka:
  instance:
    prefer-ip-addres: true
  client: 
    fenth-registry: true
    register-with-eureka: true
    services-url:
      defaultZone: http://localhost:8761/eureka
